apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gh-workflow-demo
  name: gh-workflow-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-workflow-demo
  template:
    metadata:
      labels:
        app: gh-workflow-demo
    spec:
      containers:
        - image: ghcr.io/xadamz23/gh-workflow-demo:sha-470c201
          name: gh-workflow-demo
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 80Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gh-workflow-demo
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: gh-workflow-demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
